name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      # This step builds the project using Maven, running the compile and package phases.
      - name: Build with Maven
        run: mvn clean install -f pom.xml

      # The mvn verify command not only runs unit tests but also runs any integration tests and ensures that the integration phase of the Maven lifecycle is executed.
      - name: Run integration tests
        run: mvn verify

      - name: Run Checkstyle
        run: mvn checkstyle:check || true

      # This step uploads the build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/*.jar


