name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run unit tests
        run: mvn test

      - name: Run integration tests
        run: mvn verify

      - name: Run Checkstyle
        run: mvn checkstyle:check || true
        continue-on-error: true

      - name: Run PMD
        run: mvn pmd:pmd
        continue-on-error: true

      - name: Generate test coverage report
        run: mvn jacoco:report

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco

      - name: Run Dependency-Check
        run: mvn dependency-check:check